In [1]:
import numpy as np

## reshape

行列の形を変える

In [2]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
x = x.reshape((4,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
x.shape

(4, 5)

In [5]:
x2 = x.astype(np.float16)
x2

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float16)

In [6]:
x.dtype

dtype('int32')

### 演習問題①
1. 100から119までの要素を持ったベクトルaを作る
2. aを2x10行列に変形
3. aを単精度浮動小数点数にキャスト変換


In [7]:
a = np.arange(100,120)
a.reshape((2,10))
a = a.astype(np.float32)
a

array([100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119.],
      dtype=float32)

### 転置

In [8]:
x2 = x.T

x2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [9]:
x2.shape

(5, 4)

### 値の代入

特定要素を置き換え

In [10]:
x2[0,0] = 100

x2

array([[100,   5,  10,  15],
       [  1,   6,  11,  16],
       [  2,   7,  12,  17],
       [  3,   8,  13,  18],
       [  4,   9,  14,  19]])

横ベクトルを置き換え

In [11]:
x2[1] = np.arange(100,104)

x2

array([[100,   5,  10,  15],
       [100, 101, 102, 103],
       [  2,   7,  12,  17],
       [  3,   8,  13,  18],
       [  4,   9,  14,  19]])

縦ベクトルを置き換え

In [12]:
x2[:,-1] = np.arange(1000,1005)
x2

array([[ 100,    5,   10, 1000],
       [ 100,  101,  102, 1001],
       [   2,    7,   12, 1002],
       [   3,    8,   13, 1003],
       [   4,    9,   14, 1004]])

### 演習問題②

x2の0行3列目の要素を99に上書き

In [13]:
x2[0,2]=99
x2

array([[ 100,    5,   99, 1000],
       [ 100,  101,  102, 1001],
       [   2,    7,   12, 1002],
       [   3,    8,   13, 1003],
       [   4,    9,   14, 1004]])

## スライス

複数の行をスライス

In [14]:
x2[0:2]

array([[ 100,    5,   99, 1000],
       [ 100,  101,  102, 1001]])

複数の列をスライス

In [15]:
x2[:,1:3]

array([[  5,  99],
       [101, 102],
       [  7,  12],
       [  8,  13],
       [  9,  14]])

### 演習問題③

x2から2~3行目の3列目をスライス

In [16]:
x2[2:4,2]

array([12, 13])