# np.arrayの使い方

## np.arrayの作り方

In [1]:
import numpy as np

In [8]:
def object_checker(obj):
    print("型：",type(obj))
    print("中身：",obj)
    if type(obj) == np.ndarray:
        print("行列のshape：",obj.shape)

In [9]:
list1 = [1,2,3]

object_checker(list1)

型： <class 'list'>
中身： [1, 2, 3]


In [10]:
arr1 = np.array(list1)

object_checker(arr1)

型： <class 'numpy.ndarray'>
中身： [1 2 3]
行列のshape： (3,)


In [11]:
list2 = [[1,2,3], [4,5,6]]
arr2 = np.array(list2)

object_checker(arr2)

型： <class 'numpy.ndarray'>
中身： [[1 2 3]
 [4 5 6]]
行列のshape： (2, 3)


## numpy関数によるnp.arrayの初期化
numpyはPythonに配列(np.array)を提供します。  
このnp.arrayはリストやtupleを元に作るだけでなく、np.zeros、np.onesなどの関数からも作ることができます。

① np.zerosを使って要素数10の配列を作ってください。

② np.onesを使ってshape (10,5)の行列を作ってください。

③ np.arangeを使って0～9までの値を持ったベクトルを作ってください。  

___hint: np.arangeはrangeとほぼ同様の動作をします。___

### np.arrayのshapeの変更

np.arrayはデータを効率的に扱うために、numpyの関数だけで配列の形を変形する事ができます。

もっとも代表的な方法として、np.reshapeがあります。

In [37]:
arr3 = np.arange(20)
arr4 = np.reshape(arr3, (10,2)) # arr3.reshape((10,2))でも可

print(
    "オリジナル：\n",arr3,
    "\nreshape後：\n",arr4
)

オリジナル：
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 
reshape後：
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


④ ゼロで初期化した要素数30の配列を、5x2x3の三階テンソルに変換してください。

### 行列の転置

In [95]:
arr5 = arr4.T
arr5

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

## np.arrayの演算
numpy.arrayは高速な行列演算が可能です。

また、計算の結果は尤もらしい型になります。  

arr1の要素はint32ですが、1.0などのfloat64と演算する事で、計算結果result1がfloat64として出力されます。

### 加算

In [13]:
result1 = arr1 +1.0
result1

array([ 2.,  3.,  4.])

In [23]:
print("arr1.dtype:",arr1.dtype)
print("result1.dtype:", result1.dtype)

arr1.dtype: int32
result1.dtype: float64


### 減算

In [18]:
result2 = result1 - 5.0
result2

array([-3., -2., -1.])

### 乗算

In [20]:
result3 = result2 * 1.5
result3

array([-4.5, -3. , -1.5])

### 除算

In [54]:
result4 = result3 / 3.0
result4

array([-1.5, -1. , -0.5])

### 剰余

In [55]:
result5 = result4 % 2
result5

array([ 0.5,  1. ,  1.5])

### 等式

In [57]:
result6 = result5 ==1
result6

array([False,  True, False], dtype=bool)

### 不等式

In [73]:
result7 = result5 !=1
result7

array([ True, False,  True], dtype=bool)

In [74]:
result8 = result5 >=1
result8

array([False,  True,  True], dtype=bool)

In [75]:
result8 = result5 <1
result8

array([ True, False, False], dtype=bool)

### 要素が含まれているか確認する

In [59]:
1 in result5

True

In [60]:
2 in result5

False

In [61]:
1 not in result5

False

In [62]:
2 not in result5

True

⑤  以下の1～5までの処理をして答えを返す関数を作成して、実行してください。

1. 1～20までの要素を持ったベクトルを用意
2. ベクトルをreshapeし2x10行列に変換
3. 配列の各要素を20倍
4. 配列の各要素のmod 3をとる
5. 配列の0をTrue、それ以外をFalseに変換
6. 5の答えをreturn